version: '3.3'

services:
  postgres:
    image: postgres:16
    container_name: postgres_n8n
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8npass
      POSTGRES_DB: n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data

  n8n:
<<<<<<< HEAD
    build:
      context: .
=======
    image: n8nio/n8n:stable
>>>>>>> ff3a265d3bcd528678d4cc3580dd2aa7a4ce176f
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgres
      - DB_POSTGRES_HOST=postgres
      - DB_POSTGRES_PORT=5432
      - DB_POSTGRES_DATABASE=n8n
      - DB_POSTGRES_USER=n8n
      - DB_POSTGRES_PASSWORD=n8npass
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_TUNNEL_SUBDOMAIN=rodrigon8n
      - WEBHOOK_TUNNEL_URL=https://rodrigon8n.hooks.n8n.cloud

    depends_on:
      - postgres
    volumes:
      - n8n_data:/home/node/.n8n

  stirling-pdf:
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
    ports:
      - "8080:8080"
    volumes:
      - ./StirlingPDF/trainingData:/usr/share/tessdata # Required for extra OCR languages
      - ./StirlingPDF/extraConfigs:/configs
      - ./StirlingPDF/customFiles:/customFiles/
      - ./StirlingPDF/logs:/logs/
      - ./StirlingPDF/pipeline:/pipeline/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - LANGS=en_GB

volumes:
  postgres_data:
  n8n_data:
# test