
services:
  postgres:
    image: postgres:16
    container_name: postgres_n8n
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8npass
      POSTGRES_DB: n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - appnet
  
  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=reforma_tributaria_consumo
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    ports:
      - "3306:3306"
    volumes:
      - .data/mariadb:/var/lib/mysql
    networks:
      - appnet

  n8n:
    image: n8nio/n8n:2.2.4
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgres
      - DB_POSTGRES_HOST=postgres
      - DB_POSTGRES_PORT=5432
      - DB_POSTGRES_DATABASE=n8n
      - DB_POSTGRES_USER=n8n
      - DB_POSTGRES_PASSWORD=n8npass
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_TUNNEL_SUBDOMAIN=rodrigon8n
      - WEBHOOK_TUNNEL_URL=https://rodrigon8n.hooks.n8n.cloud
      - N8N_STIRLING_PDF_URL=http://stirling-pdf:8080
      - DB_MARIADB_HOST=mariadb
      - DB_MARIADB_PORT=3306
      - DB_MARIADB_DATABASE=reforma_tributaria_consumo
      - DB_MARIADB_USER=user
      - DB_MARIADB_PASSWORD=pass
      
    depends_on:
      - postgres
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - appnet

  # gotenberg:
  #     image: gotenberg/gotenberg:8
  #     restart: always
  #     ports:
  #       - "3000:3000"
  #     networks:
  #       - appnet

  # stirling-pdf:
  #   image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./StirlingPDF/trainingData:/usr/share/tessdata
  #     - ./StirlingPDF/extraConfigs:/configs
  #     - ./StirlingPDF/customFiles:/customFiles/
  #     - ./StirlingPDF/logs:/logs/
  #     - ./StirlingPDF/pipeline:/pipeline/
  #   environment:
  #     - DOCKER_ENABLE_SECURITY=false
  #     - LANGS=en_GB
  #     - SERVER_SERVE_API=true
  #     - SERVER_API_ALLOW_ORIGIN=*
  #     - SECURITY_CUSTOMGLOBALAPIKEY=
  #     - SERVER_ADDRESS=0.0.0.0
  #   networks:
  #     - appnet

volumes:
  postgres_data:
  n8n_data:

networks:
  appnet:
    driver: bridge